spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxxxxx?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: xxxxx
    password: xxxxxxxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.mario: debug
  file:
    path: log/blog-dev.log
server:
  port: 8080


